- name: Checkout
  uses: actions/checkout@v4
  with:
    fetch-depth: 0
    ref: main

# Диагностика: увидеть, что реально в рабочей папке
- name: List files
  run: |
    pwd
    ls -la
    echo "---- tree (top level) ----"
    ls -la bot || true
    ls -la tests || true

# Копируем весь репозиторий (точка = всё из корня)
- name: Upload project to VPS (copy all)
  uses: appleboy/scp-action@v0.1.7
  with:
    host: ${{ secrets.VPS_HOST }}
    username: root
    password: ${{ secrets.VPS_PASSPHRASE }}
    source: |
         bot/**
         tests/**
         requirements.txt
    target: ${{ secrets.VPS_PATH }}
    overwrite: true

- name: Build on VPS & restart
  uses: appleboy/ssh-action@v1.2.0
  with:
    host: ${{ secrets.VPS_HOST }}
    username: root
    password: ${{ secrets.VPS_PASSPHRASE }}
    script: |
      set -e
      mkdir -p "${{ secrets.VPS_PATH }}"
      cd "${{ secrets.VPS_PATH }}"
      [ -d .venv ] || python3 -m venv .venv
      . .venv/bin/activate
      python -m pip install --upgrade pip
      python -m pip install -r requirements.txt

      cat > .env <<'ENV'
      TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
      OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
      OPENAI_ORG=${{ secrets.OPENAI_ORG }}
      OPENAI_BASE_URL=${{ secrets.OPENAI_BASE_URL }}
      MODEL_REASONING=${{ secrets.MODEL_REASONING }}
      MODEL_FRIENDLY=${{ secrets.MODEL_FRIENDLY }}
      DEBUG=${{ secrets.DEBUG }}
      ENV

      mkdir -p artifacts/db artifacts/compare
      systemctl daemon-reload || true
      systemctl restart medassistant.service || true
      systemctl --no-pager -l status medassistant.service || true
